### ISSUE TITLE
Connect to already running Browser

### ISSUE THREAD

**Issue by andrew-sumner** [dzharii/swd-recorder#34]
1. Is it possible to connect to an already running firefox browser started by WebDriver?  I am developing my tests in Java and would like to have the test drive the application to a particular page and then have SWD Recorder take over so I can generate the page object for the current page.

2. What is the "Use remote hub connection" option on the first page of the application for?  I haven't seen in mentioned anywhere.

Thanks
  Andrew

**Comment by dzharii** [comment]
Hi @andrew-sumner, 

> Is it possible to connect to an already running firefox browser started by WebDriver? I am developing my tests in Java and would like to have the test drive the application to a particular page and then have SWD Recorder take over so I can generate the page object for the current page.

No, unfortunately, Page Recorder cannot connect to the existing browser, because Webdriver itself does not support this scenario. And there is no way to reuse the browser session without applying some dirty hacks. I am not planning to go that way ;) 


> What is the "Use remote hub connection" option on the first page of the application for? I haven't seen in mentioned anywhere.
Normally, you do not need to use this option. Enabling this option allows you to connect to remote webdriver node ([RemoteWebDriverServer](https://code.google.com/p/selenium/wiki/RemoteWebDriverServer)) or Selenium Grid or local selenium server (selenium-server.jar). 
You might use this option for testing the RemoteDriver connection to the remote machine. Also, it allows you to use HTMLUnitDriver.
At this point, this feature is close to be useless. In future releases, it will enable Page Recorder to connect to Appium and the other external  WebDriver remote servers.

- Dima
